#!/bin/bash

u=0
k=0

until [ $# -eq 0 ]; do
  if test $1 = "-u"; then
    u=1;
    shift
  elif test $1 = "-k"; then
    k=$2
    shift
    shift
  else
    echo "cannot find valid argument"
    shift
  fi
done

if (( u == 0 )); then
  cipher=$(./create_pattern -k $k)
else
  cipher=$(./create_pattern -u -k $k)
fi

while read -r line; do 
  var=$(echo $line | tr A-Z $cipher)
  echo $var
done


